name: "WhittakerTech"
tagline: "Game Development & Technical Services"
title: "WhittakerTech - Game Development & Technical Services"
description: >-
  A technology blog covering web development, DevOps, and software engineering.
baseurl: ""
url: "https://whittakertech.com"

author:
  name: "Lee Whittaker"
  email: "lee@whittakertech.com"
  twitter: "whittakertech"
  linkedin: "lee-whittaker-dev"

repository: whittakertech/jekyll-blog
github:
  repository_name: jekyll-blog
  owner_name: whittakertech

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

# Critical: This matches your sitemap exactly
permalink: /blog/:title/

# Sass configuration for Tailwind integration
sass:
  sass_dir: assets/css
  style: compressed

# Feed configuration for better SEO
feed:
  posts_limit: 20
  excerpt_only: true

# SEO optimization
timezone: America/Denver  # Your timezone for proper dates

# Social media defaults (customize as needed)
twitter:
  username: whittakertech
  card: summary_large_image

# Collections
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:title/  # Redundant but explicit
  portfolio:
    output: true
    permalink: /portfolio/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lee Whittaker"
      robots: "index, follow"
      sitemap: true
      excerpt_separator: "<!--more-->"
      schema_type: "BlogPosting"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      robots: "index, follow"
      sitemap: true
  - scope:
      path: "blog"
    values:
      layout: "blog"
      robots: "index, follow"
      sitemap: true
  - scope:
      path: "portfolio"
    values:
      layout: "portfolio"
      robots: "index, follow"
      sitemap: true

# Pagination for blog index
paginate: 10
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - .idea/
  - Dockerfile
  - docker-compose.yml
  - vendor/
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github/
  - scripts/
  - Makefile
  - "*.sh"
  - node_modules/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/css/input.css  # Exclude the input file, include the output

# Include the compiled CSS
include:
  - assets/css/output.css