title: WhittakerTech
description: >-
  A technology blog covering web development, DevOps, and software engineering.
baseurl: ""
url: "https://whittakertech.com"

repository: whittakertech/jekyll-blog
github:
  repository_name: jekyll-blog
  owner_name: whittakertech

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lee Whittaker"
      robots: "index, follow"
      sitemap: true
      excerpt_separator: "<!--more-->"
      schema_type: "BlogPosting"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      robots: "index, follow"
      sitemap: true

# Exclude from processing
exclude:
  - .idea/
  - Dockerfile
  - docker-compose.yml
  - vendor/
  - README.md
  - Gemfile
  - Gemfile.lock