services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - JEKYLL_ENV=development
      - PAGES_REPO_NWO=whittakertech/jekyll-blog
    stdin_open: true
    tty: true
    working_dir: /app
    # Enhanced command that builds CSS and starts Jekyll with live reload
    command: >
      sh -c "
        bundle install &&
        npm install &&
        bundle exec foreman start -f Procfile.dev
      "

volumes:
  bundle_cache:
  node_modules: