services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - JEKYLL_ENV=development
      - PAGES_REPO_NWO=whittakertech/jekyll-blog
    stdin_open: true
    tty: true
    working_dir: /app
    # Enhanced command that builds CSS and starts Jekyll with live reload
    command: >
      sh -c "
        npm install &&
        npm run build:css &
        bundle exec jekyll serve --host 0.0.0.0 --livereload --incremental
      "

volumes:
  bundle_cache:
  node_modules: